### ISSUE TITLE
Do you have any ideas for WhatsApp to resume chat

### ISSUE THREAD

**Issue by huangpd** [tolgatasci/whatsapp-api-appium#1]
If this number is blocked, I want to transfer the chat record

**Comment by tolgatasci** [comment]
/data/data/com.whatsapp/databases/msgstore.db

For example, when you look at the message table. What changes out of normal? In the blocked state

If we know the situation on the side in sql, you can do whatever you want.

https://www.sqlitetutorial.net/sqlite-case/

**Comment by huangpd** [comment]
thanks
